version: "3.7"

volumes:
  server_node_modules:

services:
  server:
    build: ./server
    volumes:
      - "server_node_modules:/app/node_modules"
      - "./server:/app"
    ports:
      - "4774:8080"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      SERVER_HOST: ${SERVER_HOST}
